version: '3'
services:
  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
  express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
